--
-- PostgreSQL database dump
--

\restrict OfDWkIjchvtV3AY7X0GmbkmnpuGxBKninsxeUVu26HVQrB9sDOjp6tKru53L5I8

-- Dumped from database version 18.1 (Homebrew)
-- Dumped by pg_dump version 18.1 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: persona-management_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."persona-management_account" (
    "userId" character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    "providerAccountId" character varying(255) NOT NULL,
    refresh_token text,
    access_token text,
    expires_at integer,
    token_type character varying(255),
    scope character varying(255),
    id_token text,
    session_state character varying(255)
);


ALTER TABLE public."persona-management_account" OWNER TO postgres;

--
-- Name: persona-management_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."persona-management_post" (
    id integer NOT NULL,
    name character varying(256),
    "createdById" character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."persona-management_post" OWNER TO postgres;

--
-- Name: persona-management_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."persona-management_post" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."persona-management_post_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona-management_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."persona-management_session" (
    "sessionToken" character varying(255) NOT NULL,
    "userId" character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL
);


ALTER TABLE public."persona-management_session" OWNER TO postgres;

--
-- Name: persona-management_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."persona-management_user" (
    id character varying(255) NOT NULL,
    name character varying(255),
    email character varying(255) NOT NULL,
    "emailVerified" timestamp with time zone,
    image character varying(255)
);


ALTER TABLE public."persona-management_user" OWNER TO postgres;

--
-- Name: persona-management_verification_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."persona-management_verification_token" (
    identifier character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL
);


ALTER TABLE public."persona-management_verification_token" OWNER TO postgres;

--
-- Data for Name: persona-management_account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."persona-management_account" ("userId", type, provider, "providerAccountId", refresh_token, access_token, expires_at, token_type, scope, id_token, session_state) FROM stdin;
\.


--
-- Data for Name: persona-management_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."persona-management_post" (id, name, "createdById", "createdAt", "updatedAt") FROM stdin;
\.


--
-- Data for Name: persona-management_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."persona-management_session" ("sessionToken", "userId", expires) FROM stdin;
\.


--
-- Data for Name: persona-management_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."persona-management_user" (id, name, email, "emailVerified", image) FROM stdin;
\.


--
-- Data for Name: persona-management_verification_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."persona-management_verification_token" (identifier, token, expires) FROM stdin;
\.


--
-- Name: persona-management_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."persona-management_post_id_seq"', 1, false);


--
-- Name: persona-management_account persona-management_account_provider_providerAccountId_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_account"
    ADD CONSTRAINT "persona-management_account_provider_providerAccountId_pk" PRIMARY KEY (provider, "providerAccountId");


--
-- Name: persona-management_post persona-management_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_post"
    ADD CONSTRAINT "persona-management_post_pkey" PRIMARY KEY (id);


--
-- Name: persona-management_session persona-management_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_session"
    ADD CONSTRAINT "persona-management_session_pkey" PRIMARY KEY ("sessionToken");


--
-- Name: persona-management_user persona-management_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_user"
    ADD CONSTRAINT "persona-management_user_pkey" PRIMARY KEY (id);


--
-- Name: persona-management_verification_token persona-management_verification_token_identifier_token_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_verification_token"
    ADD CONSTRAINT "persona-management_verification_token_identifier_token_pk" PRIMARY KEY (identifier, token);


--
-- Name: account_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_user_id_idx ON public."persona-management_account" USING btree ("userId");


--
-- Name: created_by_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX created_by_idx ON public."persona-management_post" USING btree ("createdById");


--
-- Name: name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX name_idx ON public."persona-management_post" USING btree (name);


--
-- Name: t_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX t_user_id_idx ON public."persona-management_session" USING btree ("userId");


--
-- Name: persona-management_account persona-management_account_userId_persona-management_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_account"
    ADD CONSTRAINT "persona-management_account_userId_persona-management_user_id_fk" FOREIGN KEY ("userId") REFERENCES public."persona-management_user"(id);


--
-- Name: persona-management_post persona-management_post_createdById_persona-management_user_id_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_post"
    ADD CONSTRAINT "persona-management_post_createdById_persona-management_user_id_" FOREIGN KEY ("createdById") REFERENCES public."persona-management_user"(id);


--
-- Name: persona-management_session persona-management_session_userId_persona-management_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."persona-management_session"
    ADD CONSTRAINT "persona-management_session_userId_persona-management_user_id_fk" FOREIGN KEY ("userId") REFERENCES public."persona-management_user"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict OfDWkIjchvtV3AY7X0GmbkmnpuGxBKninsxeUVu26HVQrB9sDOjp6tKru53L5I8

