services:
  directus:
    image: directus/directus@sha256:eb326f679ae847c0a776f93b972761dc2ebe84980e0b9d274a6bc31cd62809f7
    container_name: directus
    restart: unless-stopped
    ports:
      - "127.0.0.1:8055:8055"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - directus_uploads:/directus/uploads
    environment:
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      DB_CLIENT: "pg"
      DB_HOST: "postgres-internal"
      DB_PORT: "5432"
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
      - persona-management-internal

volumes:
  directus_uploads:

networks:
  persona-management-internal:
    external: true
