CREATE TABLE "account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "candidate_contact_type" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_language_level" (
	"value" varchar(10) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_language" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_position" (
	"value" varchar(100) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_skill" (
	"value" varchar(255) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_source" (
	"value" varchar(100) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate_status_option" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "candidate" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"fullName" varchar(255) NOT NULL,
	"city" varchar(255),
	"salaryExpectation" integer,
	"salaryCurrency" varchar(10) DEFAULT 'UZS',
	"currentPosition" varchar(255),
	"source" varchar(255),
	"status" varchar(50) DEFAULT 'new',
	"resumeUrl" varchar(500),
	"resumeFileName" varchar(255),
	"resumeFileSize" varchar(50),
	"experience" varchar(255),
	"matchScore" integer,
	"aiAnalysis" text,
	"contacts" json DEFAULT '[]'::json,
	"skills" json DEFAULT '[]'::json,
	"languages" json DEFAULT '[]'::json,
	"tags" json DEFAULT '[]'::json,
	"workExperience" json DEFAULT '[]'::json,
	"education" json DEFAULT '[]'::json,
	"notes" json DEFAULT '[]'::json,
	"activities" json DEFAULT '[]'::json,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "recent_activity_log" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"entityType" varchar(50) NOT NULL,
	"entityId" varchar(255) NOT NULL,
	"actorUserId" varchar(255),
	"actorName" varchar(255) NOT NULL,
	"action" varchar(255) NOT NULL,
	"targetName" varchar(255) NOT NULL,
	"targetStatus" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"password" varchar(255),
	"passwordChangedAt" timestamp with time zone,
	"hasSeenWelcomeModal" boolean DEFAULT true NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255),
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "vacancy" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"level" varchar(100),
	"status" varchar(50) DEFAULT 'active',
	"city" varchar(255),
	"responses" integer DEFAULT 0,
	"workType" varchar(100),
	"salaryExpectation" integer,
	"salaryCurrency" varchar(10) DEFAULT 'UZS',
	"workScheduleStart" varchar(10) DEFAULT '09:00',
	"workScheduleEnd" varchar(10) DEFAULT '18:00',
	"comments" text,
	"tasks" text,
	"team" text,
	"companyDescription" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vacancy_level_option" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vacancy_status_option" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vacancy_work_type_option" (
	"value" varchar(50) PRIMARY KEY NOT NULL,
	"label" varchar(255) NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post" ADD CONSTRAINT "post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recent_activity_log" ADD CONSTRAINT "recent_activity_log_actorUserId_user_id_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "candidate_name_idx" ON "candidate" USING btree ("fullName");--> statement-breakpoint
CREATE INDEX "candidate_city_idx" ON "candidate" USING btree ("city");--> statement-breakpoint
CREATE INDEX "candidate_created_at_idx" ON "candidate" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "recent_activity_created_at_idx" ON "recent_activity_log" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "recent_activity_entity_idx" ON "recent_activity_log" USING btree ("entityType","entityId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "vacancy_title_idx" ON "vacancy" USING btree ("title");--> statement-breakpoint
CREATE INDEX "vacancy_status_idx" ON "vacancy" USING btree ("status");