-- Seed mock candidates
INSERT INTO "persona-management_candidate" (
  "id", "fullName", "city", "salaryExpectation", "salaryCurrency",
  "currentPosition", "source", "status", "resumeUrl", "resumeFileName",
  "resumeFileSize", "experience", "matchScore", "contacts", "skills",
  "languages", "tags", "workExperience", "education", "notes", "activities", "createdAt"
) VALUES
(
  'cand-001',
  'Якупов Алмас Алчинович',
  'Ташкент',
  4000,
  'USD',
  'frontend_developer',
  'hh.uz',
  'offer',
  '/api/resume/yakupovalmas.pdf',
  'yakupovalmas.pdf',
  '12MB',
  'СТАЖ 5+ ЛЕТ',
  92,
  '[{"type":"phone","value":"+99899 123 45 67"},{"type":"telegram","value":"@yasminayak"},{"type":"email","value":"yasminerim@gmail.com"}]'::json,
  '["React","TypeScript","JavaScript"]'::json,
  '[{"name":"Русский","level":"C2"},{"name":"English","level":"C1"}]'::json,
  '["ENGLISH C1","SENIOR","ВОЗРАСТ 25+"]'::json,
  '[{"company":"Tech Solutions Inc.","position":"NETWORK ENGINEER","period":"ЯНВАРЬ 2024 - СЕЙЧАС","isCurrent":true,"description":["Мы занимаемся разработкой и поддержкой веб-приложений, активно участвуем в командных проектах","Тщательная отладка кода, чтобы обеспечить высокое качество и надежность программного обеспечения."]},{"company":"Globex International","position":"SENIOR SYSTEMS ARCHITECT","period":"ФЕВРАЛЬ 2022 - ЯНВАРЬ 2023","isCurrent":false,"description":["Участвую в проектировании и развертывании облачных инфраструктур, обеспечивая их масштабируемость и безопасность.","Занимаюсь автоматизацией процессов разработки и внедрения, используя современные инструменты и практики DevOps."]}]'::json,
  '[{"institution":"Inha University in Tashkent","gpa":"GPA 4.5","period":"ЯНВАРЬ 2025 - СЕЙЧАС","isCurrent":true},{"institution":"Inha University in Tashkent","gpa":"GPA 4.5","period":"ЯНВАРЬ 2024 - СЕЙЧАС","isCurrent":true}]'::json,
  '[{"id":"note-1","content":"Оставьте заметку...","author":"Эльвира Ахметова","createdAt":"2024-01-15"},{"id":"note-2","content":"Этот кандидат не имеет международных сертификатов, но знает испанский и французский языки","author":"Эльвира Ахметова","createdAt":"2024-01-14"}]'::json,
  '[{"id":"act-1","userName":"Эльвира Ахметова","userAvatar":"https://api.dicebear.com/7.x/avataaars/svg?seed=Elvira","action":"Изменил(а) статус кандидата","targetName":"Ахмедова А. А","targetStatus":"Нанят","timeAgo":"Только что"},{"id":"act-2","userName":"Анна Иванова","userAvatar":"https://api.dicebear.com/7.x/avataaars/svg?seed=Anna","action":"Изменил(а) статус кандидата","targetName":"Мамасаидов М. М","targetStatus":"Архивирован","timeAgo":"1 день назад"}]'::json,
  '2025-09-24T00:00:00Z'
),
(
  'cand-002',
  'Якупов Алмас Алчинович',
  'Ташкент',
  3500,
  'USD',
  'backend_developer',
  'hh.uz',
  'offer',
  NULL,
  NULL,
  NULL,
  'СТАЖ 3+ ЛЕТ',
  85,
  '[{"type":"phone","value":"+99890 987 65 43"},{"type":"telegram","value":"@almas_dev"}]'::json,
  '["Node.js","Python"]'::json,
  '[{"name":"Русский","level":"C2"}]'::json,
  '["SENIOR","ВОЗРАСТ 25+"]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '2025-09-24T00:00:00Z'
),
(
  'cand-003',
  'Нурматов Тургунбек Султанович',
  'Самарканд',
  2500,
  'USD',
  'fullstack_developer',
  'hh.uz',
  'interview',
  NULL,
  NULL,
  NULL,
  'СТАЖ 2+ ЛЕТ',
  78,
  '[{"type":"phone","value":"+99891 555 44 33"},{"type":"email","value":"nurmatov@gmail.com"}]'::json,
  '["React","Node.js","TypeScript"]'::json,
  '[{"name":"Русский","level":"C2"},{"name":"Узбекский","level":"C2"}]'::json,
  '["MIDDLE","ВОЗРАСТ 25+"]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '2025-09-24T00:00:00Z'
),
(
  'cand-004',
  'Абдурахманов Шерзодбек Тохирович',
  'Бухара',
  3000,
  'USD',
  'backend_developer',
  'hh.uz',
  'hired',
  NULL,
  NULL,
  NULL,
  'СТАЖ 4+ ЛЕТ',
  88,
  '[{"type":"phone","value":"+99893 111 22 33"},{"type":"telegram","value":"@sherzod_dev"}]'::json,
  '["Python","JavaScript"]'::json,
  '[{"name":"Русский","level":"C1"},{"name":"Узбекский","level":"C2"}]'::json,
  '["SENIOR","ВОЗРАСТ 25+"]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '[]'::json,
  '2025-09-24T00:00:00Z'
);

-- Seed mock vacancies
INSERT INTO "persona-management_vacancy" (
  "id", "title", "level", "status", "city", "responses", "workType", "createdAt"
) VALUES
  ('vac-001', 'Frontend Developer', 'Senior', 'active', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-002', 'UX Researcher', 'Senior', 'active', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-003', 'Technical Writer', 'Junior', 'active', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-004', 'Backend Engineer', 'Junior', 'draft', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-005', 'Data Scientist', 'Lead', 'paused', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-006', 'Project Manager', 'Senior', 'closed', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-007', 'Product Manager', 'Middle', 'archive', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-008', 'Software Engineer', 'Junior', 'archive', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-009', 'Mobile Developer', 'Middle', 'archive', 'Ташкент', 24, 'Гибрид', NOW()),
  ('vac-010', 'Data Analyst', 'Lead', 'archive', 'Ташкент', 24, 'Гибрид', NOW());
