DO $$
BEGIN
	IF to_regclass('public.candidate_vacancy') IS NOT NULL
		AND to_regclass('public.vacancy_candidate') IS NULL THEN
		ALTER TABLE "candidate_vacancy" RENAME TO "vacancy_candidate";
	END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = 'public'
			AND table_name = 'vacancy_candidate'
			AND column_name = 'candidateId'
	) THEN
		ALTER TABLE "vacancy_candidate" RENAME COLUMN "candidateId" TO "candidate_id";
	END IF;

	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = 'public'
			AND table_name = 'vacancy_candidate'
			AND column_name = 'vacancyId'
	) THEN
		ALTER TABLE "vacancy_candidate" RENAME COLUMN "vacancyId" TO "vacancy_id";
	END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP CONSTRAINT IF EXISTS "candidate_vacancy_candidateId_candidate_id_fk";
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP CONSTRAINT IF EXISTS "candidate_vacancy_vacancyId_vacancy_id_fk";
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP CONSTRAINT IF EXISTS "candidate_vacancy_candidateId_vacancyId_pk";
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP CONSTRAINT IF EXISTS "vacancy_candidate_candidate_id_foreign";
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP CONSTRAINT IF EXISTS "vacancy_candidate_vacancy_id_foreign";
--> statement-breakpoint
DROP INDEX IF EXISTS "candidate_vacancy_candidate_id_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "candidate_vacancy_vacancy_id_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "candidate_vacancy_created_at_idx";
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = 'public'
			AND table_name = 'vacancy_candidate'
			AND column_name = 'id'
	) THEN
		ALTER TABLE "vacancy_candidate"
			ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY;
	END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conrelid = 'public.vacancy_candidate'::regclass
			AND contype = 'p'
	) THEN
		ALTER TABLE "vacancy_candidate"
			ADD CONSTRAINT "vacancy_candidate_pkey" PRIMARY KEY ("id");
	END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" ALTER COLUMN "candidate_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" ALTER COLUMN "vacancy_id" SET NOT NULL;
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'vacancy_candidate_candidate_id_candidate_id_fk'
			AND conrelid = 'public.vacancy_candidate'::regclass
	) THEN
		ALTER TABLE "vacancy_candidate"
			ADD CONSTRAINT "vacancy_candidate_candidate_id_candidate_id_fk"
			FOREIGN KEY ("candidate_id")
			REFERENCES "public"."candidate"("id")
			ON DELETE cascade
			ON UPDATE no action;
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'vacancy_candidate_vacancy_id_vacancy_id_fk'
			AND conrelid = 'public.vacancy_candidate'::regclass
	) THEN
		ALTER TABLE "vacancy_candidate"
			ADD CONSTRAINT "vacancy_candidate_vacancy_id_vacancy_id_fk"
			FOREIGN KEY ("vacancy_id")
			REFERENCES "public"."vacancy"("id")
			ON DELETE cascade
			ON UPDATE no action;
	END IF;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vacancy_candidate_candidate_id_idx" ON "vacancy_candidate" USING btree ("candidate_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vacancy_candidate_vacancy_id_idx" ON "vacancy_candidate" USING btree ("vacancy_id");
--> statement-breakpoint
ALTER TABLE "vacancy_candidate" DROP COLUMN IF EXISTS "createdAt";
