server {
    listen 80;
    listen [::]:80;
    server_name talanty.uz admin.talanty.uz backend.talanty.uz;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
