import { DEFAULT_COMPANY_ID } from "~/shared/default-company";
import type { DemoVacancy } from "./types";

export const DEMO_VACANCIES: DemoVacancy[] = [
  {
    id: "aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    title: "Senior Frontend Developer",
    level: "senior",
    status: "active",
    city: "Ташкент",
    responses: 18,
    workType: "hybrid",
    salaryExpectation: 3500,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Приоритет на опыт с React и продуктовой аналитикой.",
    tasks:
      "Разработка новых интерфейсов, участие в архитектурных решениях, взаимодействие с дизайнерами и backend-командой.",
    team: "Продуктовая команда из 7 человек, включая PM, QA и двух backend-разработчиков.",
    companyDescription:
      "B2B SaaS-платформа для автоматизации HR-процессов с активной фазой роста.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa2-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
    title: "Product Designer",
    level: "middle",
    status: "active",
    city: "Удаленно",
    responses: 11,
    workType: "remote",
    salaryExpectation: 2400,
    salaryCurrency: "USD",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Нужен сильный UX и уверенная работа в Figma.",
    tasks:
      "Проектирование пользовательских сценариев, подготовка макетов, тестирование гипотез вместе с продакт-менеджером.",
    team: "Дизайн-команда из 3 человек, тесная связка с продуктом и разработкой.",
    companyDescription:
      "Команда строит HR-продукт для рынка Узбекистана и стран СНГ.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa3-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
    title: "HR Manager",
    level: "middle",
    status: "draft",
    city: "Ташкент",
    responses: 3,
    workType: "office",
    salaryExpectation: 14000000,
    salaryCurrency: "UZS",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Вакансия пока на согласовании бюджета.",
    tasks:
      "Полный цикл подбора, координация интервью, ведение базы кандидатов и аналитики по каналам.",
    team: "HR-команда из 2 рекрутеров и руководителя функции.",
    companyDescription:
      "Внутренняя рекрутинговая команда продуктовой компании.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa4-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
    title: "Backend Developer",
    level: "middle",
    status: "closed",
    city: "Самарканд",
    responses: 24,
    workType: "hybrid",
    salaryExpectation: 2800,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Позиция закрыта после выхода кандидата.",
    tasks:
      "Разработка API, интеграции с внешними сервисами, оптимизация производительности серверной части.",
    team: "Инженерная команда из 9 человек.",
    companyDescription:
      "Продуктовая разработка с высокой долей интеграций и автоматизации.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa5-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
    title: "Middle Fullstack Developer",
    level: "middle",
    status: "active",
    city: "Ташкент",
    responses: 16,
    workType: "hybrid",
    salaryExpectation: 3000,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Нужен уверенный опыт с React и Node.js.",
    tasks:
      "Разработка фич на frontend и backend, участие в продуктовых созвонах и ревью решений.",
    team: "Кросс-функциональная команда из 6 человек.",
    companyDescription:
      "HR-tech продукт, который масштабируется на несколько рынков.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa6-aaaa-4aaa-8aaa-aaaaaaaaaaa6",
    title: "Junior Recruiter",
    level: "junior",
    status: "active",
    city: "Ташкент",
    responses: 9,
    workType: "office",
    salaryExpectation: 9000000,
    salaryCurrency: "UZS",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Рассматриваем кандидатов с базовым опытом подбора.",
    tasks:
      "Поиск кандидатов, первичный контакт, координация интервью и ведение статусов.",
    team: "HR-функция из 4 человек.",
    companyDescription: "Внутренняя команда подбора для продуктового бизнеса.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa7-aaaa-4aaa-8aaa-aaaaaaaaaaa7",
    title: "Graphic Designer",
    level: "middle",
    status: "paused",
    city: "Удаленно",
    responses: 7,
    workType: "remote",
    salaryExpectation: 1800,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Поиск приостановлен до финализации задач бренда.",
    tasks:
      "Подготовка визуалов для маркетинга, соцсетей, сайта и рекламных кампаний.",
    team: "Маркетинг и продукт в тесной связке с дизайнером.",
    companyDescription: "Команда строит узнаваемый бренд в сегменте HR SaaS.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa8-aaaa-4aaa-8aaa-aaaaaaaaaaa8",
    title: "Project Manager",
    level: "middle",
    status: "active",
    city: "Самарканд",
    responses: 13,
    workType: "hybrid",
    salaryExpectation: 2300,
    salaryCurrency: "USD",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Нужен опыт работы с digital или продуктовой командой.",
    tasks:
      "Планирование спринтов, контроль сроков, фасилитация встреч и синхронизация команд.",
    team: "Команда из PM, дизайнеров, QA и разработчиков.",
    companyDescription: "Продуктовая компания с быстрыми релизными циклами.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaaa9-aaaa-4aaa-8aaa-aaaaaaaaaaa9",
    title: "Marketing Manager",
    level: "middle",
    status: "active",
    city: "Ташкент",
    responses: 21,
    workType: "office",
    salaryExpectation: 2000,
    salaryCurrency: "USD",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Приоритет на performance и запуск новых каналов.",
    tasks:
      "Запуск кампаний, аналитика CAC и CPL, работа с контентом и лидогенерацией.",
    team: "Маркетинг-команда из 5 человек.",
    companyDescription: "B2B компания с фокусом на рост входящего спроса.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa10-aaaa-4aaa-8aaa-aaaaaaaaaa10",
    title: "Senior Backend Engineer",
    level: "senior",
    status: "active",
    city: "Удаленно",
    responses: 19,
    workType: "remote",
    salaryExpectation: 4200,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Нужен опыт высоконагруженных API и интеграций.",
    tasks:
      "Проектирование сервисов, ревью архитектуры, оптимизация производительности и надежности.",
    team: "Backend-ядро платформы из 4 инженеров.",
    companyDescription:
      "Продукт с активным ростом клиентской базы и требований к стабильности.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa11-aaaa-4aaa-8aaa-aaaaaaaaaa11",
    title: "Talent Sourcer",
    level: "junior",
    status: "draft",
    city: "Ташкент",
    responses: 2,
    workType: "office",
    salaryExpectation: 8000000,
    salaryCurrency: "UZS",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Роль в подготовке к расширению HR-команды.",
    tasks:
      "Поиск кандидатов, оформление short-list, обновление базы и коммуникация с рекрутерами.",
    team: "Talent Acquisition команда.",
    companyDescription:
      "Внутренний подбор для быстро растущей продуктовой компании.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa12-aaaa-4aaa-8aaa-aaaaaaaaaa12",
    title: "UX Researcher",
    level: "middle",
    status: "paused",
    city: "Удаленно",
    responses: 5,
    workType: "remote",
    salaryExpectation: 2200,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Ожидаем финального утверждения бюджета.",
    tasks:
      "Проведение интервью, качественные и количественные исследования, синтез инсайтов для продукта.",
    team: "Продукт и дизайн.",
    companyDescription:
      "Команда улучшает пользовательский опыт в нескольких ключевых воронках продукта.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa13-aaaa-4aaa-8aaa-aaaaaaaaaa13",
    title: "Frontend Team Lead",
    level: "lead",
    status: "active",
    city: "Ташкент",
    responses: 14,
    workType: "hybrid",
    salaryExpectation: 4800,
    salaryCurrency: "USD",
    workScheduleStart: "10:00",
    workScheduleEnd: "19:00",
    comments: "Нужен сильный engineering leadership и hands-on опыт.",
    tasks:
      "Развитие frontend-команды, архитектурные решения, менторинг и участие в критичных задачах.",
    team: "Frontend-направление из 5 разработчиков.",
    companyDescription:
      "Продуктовая разработка с высокими требованиями к качеству интерфейсов.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa14-aaaa-4aaa-8aaa-aaaaaaaaaa14",
    title: "QA Engineer",
    level: "middle",
    status: "closed",
    city: "Ташкент",
    responses: 12,
    workType: "office",
    salaryExpectation: 1700,
    salaryCurrency: "USD",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Позиция закрыта внутренней рекомендацией.",
    tasks:
      "Функциональное тестирование, регресс, написание тест-кейсов и участие в релизных проверках.",
    team: "QA-функция из 3 человек.",
    companyDescription:
      "Команда поддерживает стабильный цикл релизов и контроль качества.",
    companyId: DEFAULT_COMPANY_ID,
  },
  {
    id: "aaaaaa15-aaaa-4aaa-8aaa-aaaaaaaaaa15",
    title: "Office Manager",
    level: "junior",
    status: "archive",
    city: "Ташкент",
    responses: 8,
    workType: "office",
    salaryExpectation: 7000000,
    salaryCurrency: "UZS",
    workScheduleStart: "09:00",
    workScheduleEnd: "18:00",
    comments: "Вакансия в архиве после реорганизации офиса.",
    tasks:
      "Поддержка офиса, координация поставщиков, организация командных мероприятий и документооборот.",
    team: "Административная поддержка офиса.",
    companyDescription:
      "Компания с гибридным форматом работы и небольшим офисом в Ташкенте.",
    companyId: DEFAULT_COMPANY_ID,
  },
];
